### ISSUE TITLE
Wrong code snippet in working-with-docker-win.md

### ISSUE THREAD

**Issue by annuit02** [UI-DataScience/info490-fa15#4]
For the first snippet of code, it should say:

docker run hello-world

instead of:

docker pull lcdm/standalone-info490

**Comment by EdwardJKim** [comment]
Do you want to submit a pull request? Instructions are [here](https://github.com/UI-DataScience/info490-fa15/blob/master/CONTRIBUTING.md).

**Comment by EdwardJKim** [comment]
No reponse after a while, the Windows guide has been fixed by admins. The same corresponding line in the Mac guide has also been fixed. Closed.
